//Register
export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCES="REGISTER_SUCCES";
export const REGISTER_FAILED="REGISTER_FAILED";

//Login
export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCES="LOGIN_SUCCES";
export const LOGIN_FAILED="LOGIN_FAILED";

//CRUD
export const ADD_PRODUCT="ADD_PRODUCT";
export const DELETE_PRODUCT="DELETE_PRODUCT";
export const UPDATE_PRODUCT="UPDATE_PRODUCT";
export const READ_ALL_PRODUCTS="READ_ALL_PRODUCTS";
export const READ_STOCK_PRODUCTS="READ_STOCK_PRODUCTS";
export const READ_BYNAME_PRODUCTS="READ_BYNAME_PRODUCTS";


